apiVersion: v1
kind: PersistentVolume
metadata:
  name: desafio-db-pv
  labels:
    app: database-desafio
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data
