apiVersion: v1
kind: Secret

metadata:
  name: desafio-db-secrets
  namespace: desafio-db

type: Opaque

data:
  # MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cm9vdDEyMw==
  MYSQL_DATABASE: cmVzdGF1cmFudGU=
  MYSQL_HOST: bXlzcWw=
  MYSQL_PORT: MzMwNg==

# echo -n "root" | base64
# echo -n "root123" | base64
# echo -n "restaurante" | base64
# echo -n "mysql" | base64
# echo -n "3306" | base64
