apiVersion: v1
kind: Secret

metadata:
  name: desafio-api-secrets
  namespace: desafio-api

type: Opaque

data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cm9vdDEyMw==
  MYSQL_DATABASE: cmVzdGF1cmFudGU=
  MYSQL_HOST: bXlzcWwuZGVzYWZpby1kYi5zdmMuY2x1c3Rlci5sb2NhbA==
  MYSQL_PORT: MzMwNg==

# para realizar a codificação em base64 dos valores, utilize o comando:
# echo -n 'seu_valor_aqui' | base64

# para conexão ao banco de dados mysql dentro do cluster, tive que colocar o nome completo do serviço (FQDN - Fully Qualified Domain Name) na variavel MYSQL_HOST:
# mysql.desafio-db.svc.cluster.local